routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/solicitudContrato');
});

Auth::routes();

Route::resource('/solicitudContrato', 'SolicitudContratoController');
Route::get('/solicitudContratoPdf/{id}', 'SolicitudContratoController@solicitudContratoPdf');
Route::get('/solicitudContratoEnviar/{id}', 'SolicitudContratoController@solicitudContratoEnviar');
Route::get('/solicitudContratoAnular/{id}', 'SolicitudContratoController@solicitudContratoAnular');
Route::get('/solicitudContratoApi/{id}', 'SolicitudContratoController@api');
Route::get('/solicitudContratoAgregarPrestacion', 'SolicitudContratoController@solicitudContratoAgregarPrestacion');

Route::resource('/user', 'UserController');
Route::get('/user/restaurar/{id}', 'UserController@restaurar');

Route::resource('/tipoContrato', 'TipoContratoController');
Route::get('/tipoContratoActivar/{id}', 'TipoContratoController@activar');

Route::resource('/tarifaHonorarioTurno', 'TarifaHonorarioTurnoController');

Route::resource('/tarifaHonorarioSumaAlzada', 'TarifaHonorarioSumaAlzadaController');

Route::resource('/tarifaProgramaChileCrece', 'TarifaProgramaChileCreceController');

Route::resource('/prestacion', 'PrestacionFuncionarioController');

Route::get('/getDatosRut', 'GetController@getDatosRut');
Route::get('/getValor', 'GetController@getValor');
Route::get('/getValorPrestacion', 'GetController@getValorPrestacion');

// Route::resource('/paciente', 'PacienteController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;

    use SoftDeletes;
    public $guarded = [];
    
    public static function boot()
    {
        parent::boot();

        static::creating(function($user)
        {
            $password = substr($user->rut, 0, 4);
            $user->password = $password;
        });
          
        static::created(function($user)
        {
            $password = substr($user->rut, 0, 4);
            $user->password = $password;
        });
    }

    public function setPasswordAttribute($value){
        $this->attributes['password'] = bcrypt(intval($value));
    }

    public function perfil()
    {
        return $this->belongsTo('App\Perfil', 'perfil_id');
    }

    public function servicio()
    {
		return $this->belongsTo('App\Servicio', 'servicio_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Perfil;
use App\Servicio;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $rut = isset($request->rut) ? str_replace(".","",request()->rut) : null;
        $users = User::with('perfil', 'servicio')
                ->when(!is_null($rut), function ($collection) use ($rut){
                    $collection->where('rut', $rut);
                }) 
                ->when($request->has('nombre') && !is_null($request->nombre), function ($collection) use ($request){
                    $collection->whereRaw("nombre LIKE ?", ['%'.$request->nombre.'%']);
                })
                ->paginate(10);
        return view('user.index', compact('users'));
    }

    public function create()
    {
        $perfiles = Perfil::get();
        $servicios = Servicio::where("bo_estado", 1)->orderBy('tx_descripcion')->get();
        return view('user.create', compact('perfiles', 'servicios'));
    }

    public function store(Request $request)
    {
        if(!isset($request->admin)){
            $request->request->add(['admin' => 0]);
        }
        $user = User::updateOrCreate(['id' => $request->id], $request->except('_token'));
        if($user){
            return redirect('/user')->with('message', $user->nombre." se ha creado correctamente");
        }else{
            return redirect('/user')->with('error', "No se ha podido crear al usuario");
        }
    }

    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        $perfiles = Perfil::get();
        $servicios = Servicio::where("bo_estado", 1)->orderBy('tx_descripcion')->get();

        return view('user.create', compact('user', 'perfiles', 'servicios'));
    }

    public function update(Request $request, User $user)
    {
        //
    }

    public function destroy(User $user)
    {
        if($user->delete()){
            return redirect('/user')->with('error', $user->nombre." a sido eliminado correctamente");
        }else{
            return redirect('/user')->with('error', "El usuario no a sido eliminado, intente nuevamente");
        }
    }

    public function restaurar($id)
    {
        $user = User::onlyTrashed()->find($id)->restore();
        return redirect('/user/'.$id.'/edit')->with('message', "Se ha restaurado el usuario correctamente");
    }
}

resources/views/user/create.blade.php
@extends('adminlte::page')

@section('title', 'Usuario')

@include('alert.notificacion')

@section('content')
    <br>
    <div class="card">
        <form role="form" class="form-horizontal" id="form" method="POST" action="{{action('UserController@store')}}">
            {{ csrf_field() }}
            <input type="hidden" id="id" name="id" value="{{$user->id ?? ''}}"/>
            <div class="card-header">
                <h3 style="color:green" class="card-title"><strong>Usuario</strong></h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-4">
                            <label for="rut">Rut<span style="color:#FF0000";>*</span></label>
                            <input type="text" class="form-control" id="rut" name="rut" value="{{$user->rut ?? ''}}" onblur="getPerson($(this).val());" required>
                        </div>
                        <div class="col-sm-4">
                            <label for="nombre">Nombre<span style="color:#FF0000";>*</span></label>
                            <input type="text" class="form-control" id="nombre" name="nombre" value="{{$user->nombre ?? ''}}" required>
                        </div>
                        <div class="col-sm-4">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{$user->email ?? ''}}">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-4">
                            <label for="perfil_id">Perfil<span style="color:#FF0000";>*</span></label>
                            <select class="form-control" id="perfil_id" name="perfil_id" onchange="servicio($(this).val());">
                                <option value="">Seleccione Perfil</option>
                                @foreach ($perfiles as $perfil)
                                    @if (Auth::user()->perfil_id == 1 || $perfil->id > 2)
                                        <option value={{$perfil->id}} {{isset($user) && $user->perfil_id == $perfil->id ? 'selected' : ''}}>{{$perfil->nombre}}</option>		
                                    @endif						
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <label for="servicio_id">Servicio</label>
                            <select class="form-control" id="servicio_id" name="servicio_id">
                                <option value="">Seleccione Servicio</option>
                                @foreach ($servicios as $servicio)
                                    <option value={{$servicio->id}} {{isset($user) && $user->servicio_id == $servicio->id ? 'selected' : ''}}>{{$servicio->tx_descripcion}}</option>								
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <br>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="admin" name="admin" value="1" {{isset($user) && $user->admin == 1 ? 'checked' : ''}}>
                                <label class="form-check-label"><strong>Administrador</strong></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-info">Guardar</button>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script>
        @include('alert.script')

        function getPerson(rut){
            $.getJSON("{{action('GetController@getDatosRut')}}?rut="+rut,
                function(data){
                    if(data.user){
						var opcion = confirm("Este Usuario ya existe desea editarlo?");
						if(opcion == true){
							location.href = data.id+"/edit";
						}else{
							$("#rut").val("");
						}
                    }else if(data.eliminado){
                        var opcion = confirm("Este Usuario fue eliminado, desea restaurarlo?");
						if(opcion == true){
							location.href = "restaurar/"+data.id;
						}else{
							$("#rut").val("");
						}
					}else{
                        if(data.error != null){
                            alert(data.error);
                            $("#rut").val(null);
                        }else{
                            $("#rut").val(data.rut);
                            $("#nombre").val(data.tx_nombre+' '+data.tx_apellido_paterno+' '+data.tx_apellido_materno);
                        }
                    }
                }
            )
        }

        function servicio(perfil){
            if(perfil == 4){
                $("#servicio_id").css('display','').attr('disabled', false);
                $("#servicio_id").css('display','').attr('required', true);
            }else{
                $("#servicio_id").css('display','').attr('disabled', true);
                $("#servicio_id").css('display','').attr('required', false);
            }
        }

        @if(isset($user))
            var user = @json($user);
            servicio(user.perfil_id);
        @else
            servicio();
        @endif
    </script>    
@endsection

resources/views/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Usuarios')

@include('alert.notificacion')

@section('content')
    <br>
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Lista de Usuarios</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <form class="form-horizontal">
                        <div class="form-group row">
                            <div class="col-sm-2">
                                <input type="text" name="rut" class="form-control" id="rut" placeholder="Rut" value="{{request()->rut}}">
                            </div>
                            <div class="col-sm-2">
                                <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre" value="{{request()->nombre}}">
                            </div>
                            <div class="col-sm-1 offset-sm-6">
                                <button type="submit" class="btn btn-info">Filtrar</button>
                            </div>
                            <div class="col-sm-1">
                                <a href={{url('user/create')}} class="btn btn-success" type="button" title="Agregar Nuevo Usuario"><i class="fa fa-plus" style="color:white"></i></a>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <th>ID</th>
                                <th>Rut</th>
                                <th>Nombre</th>
                                <th>Email</th>
                                <th>Perfil</th>
                                <th>Servicio</th>
                                <th>Admin</th>
                                <th><i class="fa fa-cog"></i></th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    @if (Auth::user()->perfil_id == 1 || $user->perfil_id > 2)
                                        <tr>
                                            <td>{{$user->id}}</td>
                                            <td>{{$user->rut}}</td>
                                            <td>{{$user->nombre}}</td>
                                            <td>{{$user->email}}</td>
                                            <td>{{$user->perfil->nombre}}</td>
                                            <td>{{$user->servicio->tx_descripcion ?? ""}}</td>
                                            <td>{{$user->admin == 1 ? 'Si' : 'No'}}</td>
                                            <td>
                                                <form action="{{ route('user.destroy',$user->id) }}" method="POST">
                                                    <div class="btn-group">
                                                        <a href={{url("user/".$user->id."/edit")}} title="Editar" class="btn btn-warning btn-xs"><i class="fa fa-edit" style="color:white"></i></a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button onclick="return confirm('¿Esta seguro de eliminar a {{$user->nombre}}?');" title="Eliminar" type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash" style="color:white"></i></button>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $users->appends(request()->query())->links() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        @include('alert.script')
    </script>
@stop